### ISSUE TITLE
Definition of 'infection'

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/IDO#5]
It's the issue that just keeps coming back ;)

We (IDO team) had arrived at the following revision of the definition of 'infection'

Infection =def. Part of an extended organism that itself has an infectious agent population as part, exists as a result of processes initiated by members of the infectious agent population, and is:
(1) Clinically abnormal in virtue of the presence of this infectious agent population or, 
(2) Has a disposition to bring clinical abnormality to immunocompetent organisms of the same Species as the host (the organism corresponding to the extended organism) through transmission of a member or offspring of a member of the infectious agent population.

An issue is its relationship to 'infectious disorder'

infectious disorder = an infection that is clinically abnormal

In the paper, we explained that the key thing is that not every infection satisfies clause 1), particularly infections within hosts that have a protective resistance to the infectious agent population (IAP) so that the IAP is not causally linked to increased risk of illness, dysfunction etc in the host. In these cases, the IAP still has a disposition to bring clinical abnormality to other potential hosts without resistance, and so satisfies clause 2). This is what ensures that not every infection is an infectious disorder. 

I pointed this out to Barry recently, but now he thinks that 1) should not be included in the definition of infection at all. I guess the rationale is that the definition should only include conditions satisfied by all instances of 'infection', but I am still waiting to hear back from him for confirmation regarding this. I will update this post once I hear back from him.

**Comment by johnbeve** [comment]
Some relevant news before jumping into the issue: 

Barry pointed out a bit ago (and I double-checked) that some diseases can be caused by a single virion which means that _viral infection_, which is a subclass of _infection_, may arise without a virus population. I adjusted the definition to allow for virion or virus population initiators, but that's not technically in line with the definition of _infection_, since _infectious agent population_ requires at least two entities in the aggregate. This is all to say I think we need to adjust the definition of _infection_ accordingly. 

Related, we'll need to expand _infection_ beyond infectious agents to allow for infectious structures too. 

The result should perhaps look something like: 

Infection =def. Part of an extended organism that itself has an infectious agent or infectious structure as part, exists as a result of processes initiated by that infectious entity, and is:
(1) Clinically abnormal in virtue of the presence of this infectious entity, or,
(2) Has a disposition to bring clinical abnormality to immunocompetent organisms of the same Species as the host (the organism corresponding to the extended organism) through transmission of a member or offspring of a member of the infectious agent population.

Now to the issue: 

If I understand correctly, Barry's idea is to impose minimal constraints on classes, and fill out child classes with the needed specifications. This is the difference between defining an infection as having A, B or C (which suggests all and only things having A, B or C count as infections) vs definition infection as A then subclasses for B and C respectively. This is useful in the event we need to adjust the definitions for some presently unforeseen reason, or to account for exceptions that arise in the future.  

Does that sound right to you?

**Comment by PhiBabs935** [comment]
Going that route would certainly making addressing Werner's objections much simpler. 

Though I did post this issue before we received W's comments, and I remember that in his reply email to Werner (which you received as well) Barry claimed that he thought the definition of infection was one of the best parts of IDO and so now I am unsure...

Would the thought be to save the stuff in the (1) and (2) for subclasses of infection? Or something like that?

**Comment by PhiBabs935** [comment]
Werner's objection is that infectious disorder is a subclass of infection, but that if you apply the right substitutions to clauses (1) and (2) infection is defined as: an infectious disorder or something that has the disposition to become an infectious disorder. (paraphrasing from his email).

Barry's reply was: 
"The fact that we can _infer_ that an infection is either an infectious disorder or something else, does not imply that that is how we _define_ infection -- and I am still confident that the definition of infection is one of the best parts of IDO. We do, know, need to address the problem (which is what threw me in the talk on Monday) that 'infectious disorder' currently has 2 parents -- infection on the one hand, and infectious disorder on the other hand."

**Comment by johnbeve** [comment]
I agree with Barry on the distinction between inferring and defining, and I'd add I think Werner simply isn't thinking carefully about the definition. 

Regarding Barry's comment, If 'infectious disorder' has 'infection' and 'infectious disorder' as parents, then that's surely a typo, since infectious disorder isn't a child of itself. 

Presently, in the owl file 'infectious disorder' is defined as the conjunction of infection and disorder. Perhaps that's what he's concerned with. If so, I think we can resolve this issue by asserting 'infectious disorder' is a subclass of 'infection', drop 'disorder' from equivalency conjunction, but add an owl axiom ensuring that 'infectious disorder' is an inferred subclass of both 'infection' and 'disorder'. 

As a matter of fact, even if this isn't what's bugging Barry, I think this is preferable to the way infection is formally defined now, which suggests multiple inheritance.

**Comment by PhiBabs935** [comment]
I am not sure what we could do for an axiom that makes 'infectious disorder' an inferred subclass of 'disorder', unless we also add an axiom to 'disorder'. Currently though only axiom for disorder is that it is a subclass of material entity.

The only thing that comes to mind is an axiom referring to clinical abnormality, but in OGMS 'clinically abnormal' is an undefined primitive that was characterized as _feature_ in the original OGMS paper. So I am not sure whether it is currently possible to add the desired axiom. If there was the resources it would look something like: subclass of: _"has some_ '_______' clinical abnormality"
where the blank is filled by a more general property, but I am not sure the resources currently exist. 

What do you think?

**Comment by johnbeve** [comment]
I'd very much like to explicate 'clinical abnormality' to resolve this and other issues, but there are other options we could pursue. 

We could instead move the other direction, defining 'infectious disorder' as a subclass of 'disorder' involving infectious agents or structures, and enough other constraints to ensure it's an inferred subclass of 'infection'. How does that sound?

**Comment by PhiBabs935** [comment]
Now that I think about it, I am not sure whether OGMS is sticking to the original characterization of 'clinically abnormal'. Werner's comment on the IDO paper regarding the example concerning HIV infections within hosts who have a protective resistance seemed to indicate that he, for one, doesn't think the original characterization is correct. I would love to get my hands on the manuscript for the new OGMS paper to see where they stand now...

I think that having it as a child of disorder is intuitive for obvious reasons. And I like the idea of defining it along those lines, properly refined. I will start thinking about ways to go with this.

**Comment by johnbeve** [comment]
Same. 

Did Brian share the OGMS development documents with you, by chance? He shared them with after my talk, and we might be able to glean where they're headed from some of the previous meeting notes.

**Comment by PhiBabs935** [comment]
Brian didn't share the documents with me.

**Comment by PhiBabs935** [comment]
Something that I think is important for our discussion of issues with IDO 'infection':

I think that the second clause of the following needs clarification: "Part of an extended organism that itself has an infectious agent population as part, exists as a result of processes initiated by members of the infectious agent population"

For instance, consider the commensal bacteria in our mouth. Does the part of the extended organism that has this bacteria population as a part exist as a result of processes initiated by that bacteria population in the intended sense? Call this question A.

The reason why I ask is this. In the IDO paper, we noted that commensal populations might initiate an infection if they end up in the wrong location, such as in the case of bacteremia. Consider the case of transient bacteremia caused by teeth brushing and flossing when commensal bacteria in our mouth get into the blood. 

In his comments, Werner suggested that this would count as a case of an infectious agent population satisfying clause (2) of 'infection'. In that case, the IDO definition would wrongly count the commensal bacteria in our mouth as an infection. The idea is that the population is disposed to bring about clinical abnormality if it gets into our bloodstream. Now, I am not sure whether this really satisfies (2), but let's suppose that it does satisfy (2) for the moment. 

If the answer to question A is "No, the part of the extended organism of which our commensal mouth bacteria population is a part does NOT exist as a result of processes initiated by that bacteria population, then it would not count as an infection even if it does satisfy (2). 

Likewise, if the same answer is correct for any commensal microbe population that may become part of an infection (if it ends up in the wrong anatomical location) then none of them would count as infections (at the time that they are in the right location) even if they satisfy clause (2). 

On the other hand, let's suppose that the answer to question A is yes. Then in that case, Werner's objection has some force. But whether the objection is correct hinges on something else in clause (2). Specifically, what sort of transmission is being referred to in this clause? 

If 'transmission' is meant in a broad sense, then the process by which our commensal mouth bacteria gets into the bloodstream during teeth brushing would count as transmission. On that reading of transmission, the bacteria in my mouth indeed has a disposition to bring clinical abnormality to an organism of the same species as me (in this case, me) by being transmitted into my blood, and thus would satisfy (2). 

But I think it clearly would NOT satisfy (2) if the use of 'transmission' is referring to pathogen transmission in the narrower sense defined by TRANS. Pathogen transmission process is clearly defined as a process in which a pathogen is transmitted to a new host, and hosts are organisms. Thus, transmission (in the broader sense) of the bacteria into the blood is not a case of pathogen transmission in the strict sense. 

Though, now that I am thinking about it, this also brings us back to issues concerning the IDO construal of 'host'. In OWL it's defined as an organism that has some host role. But in the virology literature we have been using, infected cells are routinely characterized as 'host cells' even though they are not organisms.

**Comment by PhiBabs935** [comment]
Have you thought anymore about the revisions to infection and infectious disorder?

I thought that the start might be to define _infectious disorder_, as you suggested, as something like: Disorder that has infectious agents or infectious structures as parts.

And then add the axioms: 
(_part of_ some _extended organism_) 
((_has part_ some _infectious agent_) or (_has part_ some _infectious structure_)) 
(some axiom capturing the "exists as a result of processes initiated by those infectious entities" clause from the infection definition)

*alternatively, we could add the first axiom listed above to 'disorder' instead and have it be inherited--OGMS didn't use the axiom, though they could have. 

I was hoping that if we make _infection_ into an equivalence class that includes the above axioms, then we could achieve our desired result of making _infectious disorder_ an inferred subclass of _infection_, i.e. by having it defined partly as: (_part of_ some _extended organism_) and ((_has part_ some _infectious agent_) or (_has part_ some _infectious structure_)) and (some axiom capturing the "exists as a result of processes initiated by those infectious entities" clause from the infection definition)

But the problem then becomes, what to do about clauses (1) and (2)? Do we add a further conjunct after the above, i.e. "and ((axiom covering 1) or (axiom covering 2))"? 

If so, we are once again left with the problem that I discussed in a previous comment above. How do we represent, in axiom form, the fact that something has the feature of clinical abnormality? Obviously we can't just have 

2) isn't simple either. For 2), I thought that IDO's primary infectious disposition (=def An infectious disposition to become part of a disorder in organisms that have intact defenses) might be relevant as it is a disposition to bring clinical abnormality to immunocompetent organisms. Lindsay et al added a comment where they invoke a quotation from Mandell's "Principles and Practice of Infectious Diseases". The point is that 'primary infectious disposition' is only borne by "principle" pathogens with greater virulence capabilities than other 'opportunistic' pathogens. Particularly important, it is an infectious disposition that commensals lack (using this disposition here would help us avoid the objection that commensals satisfy clause 2 just because of the fact that they are disposed to bring clinical abnormality to their host in the event that they get in the wrong location--as with commensal bacteria being disposed to bring clinical abnormality if they get into our bloodstream.)

So, the axiom covering 2 would start with something like:
(_has disposition_ some _primary infectious disposition)_. 

But there is a problem: _primary infectious disposition_ isn't restricted to transmission between organisms of the same species, whereas clause 2) specifically refers to transmission between organisms of the same species. So we need some further restriction here.
 
Transmission between organisms of the same species is covered in IDO by _horizontal pathogen transmission process_ =def A pathogen transmission process in which a pathogen is transmitted from one host to another of the same species, and the two hosts are not in a parent-child relationship.

So, we also need to represent that the infectious entities are disposed to bring clinical abnormality to another immunocompetent host of the same species via horizontal transmission. But there currently isn't any disposition in IDO that will let us do that. IDO has _communicability_, which is only realized when a pathogen is transmitted **directly** by horizontal transmission, and that disposition is disjoint with _primary infectious disposition_. I assume that is because _primary infectious disposition_ can be realized in indirect transmission processes?

**Comment by PhiBabs935** [comment]
Since we are in the process of hammering out the details of this on slack I will close this.
